FROM syncthing/syncthing:2.0.9

LABEL org.opencontainers.image.source="https://github.com/syncthing/syncthing"
LABEL org.opencontainers.image.description="Open Source Continuous File Synchronization"
