FROM syncthing/syncthing:1.30.0

LABEL org.opencontainers.image.source="https://github.com/syncthing/syncthing"
LABEL org.opencontainers.image.description="Open Source Continuous File Synchronization"
