name: Build resources

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build ignition
        run: >
          docker run --interactive --rm
          --volume ${PWD}:/pwd --workdir /pwd quay.io/coreos/butane:release
          --pretty --strict homeservices.bu > homeservices.ign
      - name: Archive ignition file
        uses: actions/upload-artifact@v3
        with:
          name: homeservices-ignition
          path: homeservices.ign
