name: Build resources

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  NAMESPACE: michamos

jobs:
  build-ignition:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build ignition
        run: >
          docker run --interactive --rm
          --volume ${PWD}:/pwd --workdir /pwd quay.io/coreos/butane:release
          --pretty --strict homeservices.bu > homeservices.ign
      - name: Archive ignition file
        uses: actions/upload-artifact@v3
        with:
          name: homeservices-ignition
          path: homeservices.ign

  list-containers:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(ls containers/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: list-containers
    strategy:
        matrix:
            image: ${{ fromJson(needs.list-containers.outputs.matrix) }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@1f401f745bf57e30b3a2800ad308a87d2ebdf14b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@62339db73c56dd749060f65a6ebb93a6e056b755
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ matrix.image }}
      - name: Build and push Docker image
        uses: docker/build-push-action@9f6f8c940b91232557f8699b21341a08624a8dce
        with:
          context: containers/${{ matrix.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
